package com.vaultpay.security.jwt;

import io.jsonwebtoken.Claims;     // represents the payload of the JWT, containing claims like subject and expiration.
import io.jsonwebtoken.JwtException;  // base exception for any JWT parsing/validation errors (e.g., signature invalid, token expired).
import io.jsonwebtoken.Jwts;            // main class for building and parsing JWTs.
import io.jsonwebtoken.security.Keys;    // utility class to create cryptographic keys for signing JWTs. Here we use it to convert our secret string into a SecretKey object.
import lombok.RequiredArgsConstructor;   // Lombok annotation to generate a constructor for final fields (like jwtProperties).
import lombok.extern.slf4j.Slf4j;         // Lombok annotation to generate a logger for this class, so we can log important events (like invalid tokens).
import org.springframework.security.core.userdetails.UserDetails; // Spring Security interface representing user information. We use it to get the username (email) when generating and validating tokens.
import org.springframework.stereotype.Service;    // Marks this class as a Spring service component, making it available for dependency injection in other parts of the application (like our authentication filter).
 
import javax.crypto.SecretKey;     // Represents the secret key used for signing and verifying JWTs. We create this from the secret string in application.yml.
import java.nio.charset.StandardCharsets;   // Used to convert the secret string into bytes when creating the SecretKey. We use UTF-8 encoding for this conversion.
import java.util.Date;                        // To create date objects

/**
 * Handles all JWT operations: generation, parsing, and validation.
 *
 * HOW JWT WORKS (brief):
 *   A JWT has 3 parts separated by dots: header.payload.signature
 *   - Header: algorithm used (HS256)
 *   - Payload (Claims): who the token is for, when it expires
 *   - Signature: HMAC of header+payload using our secret key
 *
 *   Because only our server knows the secret key, nobody can forge a valid signature.
 *   We DON'T need to store tokens in the DB. We just verify the signature on each request.
 */

@Slf4j
@Service
@RequiredArgsConstructor
public class JwtService {

    private final JwtProperties jwtProperties;

    /**
     * Generates a signed JWT for the given user.
     * The token contains the user's email as the "subject" claim.
     */
    public String generateToken(UserDetails userDetails) {
        Date now = new Date();
        Date expiry = new Date(now.getTime() + jwtProperties.getExpirationMs());

        return Jwts.builder()
        .subject(userDetails.getUsername())  // username = email in the application
        .issuedAt(now)
        .expiration(expiry)
        .signWith(getSigningKey())
        .compact();
    }


    /**
     * Extract the user's email (subject) from a token.
     * @throws JwtException if the token is invalid or expired
     */
    public String extractEmail(String token) {
        return extractAllClaims(token).getSubject();
    }

    /**
     * Validate that the token belongs to the given user and isn't expired.
     */
    public boolean isTokenValid(String token, UserDetails userDetails) {
        try {
            String email = extractEmail(token);
            return email.equals(userDetails.getUsername()) && !isTokenExpired(token);
        } catch (JwtException e) {
            log.warn("Invalid JWT: {}", e.getMessage());
            return false;
        }
    }

 // ── Private methods ───────────────────────────────────────────────────────
 
    private boolean isTokenExpired(String token) {
        return extractAllClaims(token).getExpiration().before(new Date());
    }
    
    private Claims extractAllClaims(String token) {
        // Parsing the token verifies the signature. If tampered with, an exception is thrown
        return Jwts.parser()
        .verifyWith(getSigningKey())
        .build()
        .parseSignedClaims(token)
        .getPayload();
    }

    /**
     * Convert the hex secret string from application.yml into a cryptographic key.
     * The secret must be at least 256 bits (32 bytes) for HMAC-SHA256.
     */
    private SecretKey getSigningKey() {
        byte[] keyBytes = jwtProperties.getSecret().getBytes(StandardCharsets.UTF_8);
        return Keys.hmacShaKeyFor(keyBytes);

    }
}

// this class provides methods to create JWTs when users log in, and to validate and parse those tokens on subsequent requests. 
// It uses the secret key defined in application.yml to sign and verify tokens, ensuring that only tokens generated by our server are accepted.

// application.yml: 
// jwt:
//   secret: your-256-bit-secret-key-here
//   expiration: 86400000

// application.yml is the source of truth for our JWT configuration, and JwtProperties is the type-safe way to access those values in our code.


// @Slf4j - Lombok annotation to generate a logger for this class, so we can log important events (like invalid tokens).
// @Service - Marks this class as a Spring service component, making it available for dependency injection in other parts of the application (like our authentication filter).
// @RequiredArgsConstructor - Lombok annotation that generates a constructor with required arguments (final fields). This allows us to inject JwtProperties without writing boilerplate code.

// final means the field must be initialized in the constructor and cannot be changed afterward, which is ideal for configuration properties that should not change at runtime.

// what is subject in JWT?
// The "subject" (sub) claim in a JWT is a standard claim that identifies the principal (user) that the token is issued for. 
// In our case, we set the subject to be the user's email (which is also their username in our application). 
// When we extract the email from the token later, we read it from the subject claim.

// what are claims in JWT?
// Claims are pieces of information asserted about a subject. They are stored in the payload of the JWT.
// Common claims include:
// - sub (subject): identifies the user (e.g., email)
// - exp (expiration): when the token expires